### ISSUE TITLE
Hubba

### ISSUE THREAD

**Issue by Bubba-xxx** [hudson555x/glumpkin#1]
Hey Hubba Hubba.
Looks like you got yourself a GitHub account.  Why?  You don't even know how to use the account.  It's for coders.  You can barely write a coherent English sentence
Been very posty the past few days.  Keep them comin' boo boo.  We need all the laughs you can give us.
ROFL

**Comment by hudson555x** [comment]
So I make mistakes and don't know GitHub.
Seriously, just message me on Shotcut with your real account and we can talk about this.
This the only response you'll see from me in public.
Man up dude!

![2020-11-27_01-02-19](https://user-images.githubusercontent.com/73324058/100416359-4482c280-304c-11eb-93fd-feb4cfc9e9ef.png)
![firefox_2020-11-27_01-00-49](https://user-images.githubusercontent.com/73324058/100416393-5c5a4680-304c-11eb-8d21-1b5cf1eaeefc.png)





![2020-11-27_00-44-49](https://user-images.githubusercontent.com/73324058/100415374-fff62780-3049-11eb-97ff-61e7acb5b96e.png)


![firefox_2020-11-27_00-37-45](https://user-images.githubusercontent.com/73324058/100415354-f240a200-3049-11eb-82ba-aef0c3447370.png)

![firefox_2020-11-27_00-51-50](https://user-images.githubusercontent.com/73324058/100415695-c376fb80-304a-11eb-8c06-9bd61236f1dc.png)
